// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnq6vVkXHY8_201E_PS4-VORnjPFHKXBw',
    appId: '1:972100098172:web:fa00dfae7888c1c0cf91f9',
    messagingSenderId: '972100098172',
    projectId: 'codebots-23dad',
    authDomain: 'codebots-23dad.firebaseapp.com',
    databaseURL: 'https://codebots-23dad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codebots-23dad.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCbpJIRUuoS0YG2d2_LRzDzvUVakeAw6A4',
    appId: '1:972100098172:android:bb7ed88f221d9230cf91f9',
    messagingSenderId: '972100098172',
    projectId: 'codebots-23dad',
    databaseURL: 'https://codebots-23dad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codebots-23dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeup5KnMyN3oueZhMA4eU6JjP13jEJYXg',
    appId: '1:972100098172:ios:413aaedf85257735cf91f9',
    messagingSenderId: '972100098172',
    projectId: 'codebots-23dad',
    databaseURL: 'https://codebots-23dad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codebots-23dad.appspot.com',
    iosBundleId: 'com.example.sih',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeup5KnMyN3oueZhMA4eU6JjP13jEJYXg',
    appId: '1:972100098172:ios:5334283645b1550dcf91f9',
    messagingSenderId: '972100098172',
    projectId: 'codebots-23dad',
    databaseURL: 'https://codebots-23dad-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'codebots-23dad.appspot.com',
    iosBundleId: 'com.example.sih.RunnerTests',
  );
}
