import 'package:flutter/material.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
import 'package:sih/models/dmodel.dart';

class search extends StatelessWidget {
  search({super.key});
  final List<Autogenerated> list = [];
  Future<List<Autogenerated>> getpostApi() async {
    final response =
        await http.get(Uri.parse("http://192.168.177.197:8000/doctor"));
    var data = jsonDecode(response.body.toString());
    if (response.statusCode == 200) {
      list.clear();
      for (Map i in data) {
        list.add(Autogenerated.fromJson(i));
      }
      return list;
    } else {
      return list;
    }
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: SingleChildScrollView(
        child: Container(
          width: double.infinity,
          decoration: BoxDecoration(
              gradient: LinearGradient(
            colors: [
              Color(0xffE2DEEE),
              Color(0xffCBDBEA),
            ],
            begin: Alignment.topCenter,
            end: Alignment.bottomCenter,
          )),
          child: Column(
            children: [
              SizedBox(
                height: 50,
              ),
              Padding(
                padding: const EdgeInsets.all(25.0),
                child: Text(
                  "List of Physiotherapists",
                  style: TextStyle(
                    fontFamily: "Inter",
                    fontWeight: FontWeight.w500,
                    fontSize: 30,
                  ),
                ),
              ),
              FutureBuilder(
                  future: getpostApi(),
                  builder: (context, snapshot) {
                    if (!snapshot.hasData) {
                      return Text(
                        "Loading....",
                        style: TextStyle(
                          fontFamily: "Inter",
                          fontSize: 15,
                          fontWeight: FontWeight.w500,
                        ),
                      );
                    } else {
                      return ListView.builder(
                          scrollDirection: Axis.vertical,
                          shrinkWrap: true,
                          itemCount: list.length,
                          itemBuilder: (context, index) {
                            return Padding(
                              padding: const EdgeInsets.all(15.0),
                              child: Card(
                                child: Column(
                                  children: [
                                    Row(
                                      children: [
                                        Icon(
                                          Icons.account_circle_outlined,
                                          size: 100,
                                        ),
                                        SizedBox(
                                          width: 10,
                                        ),
                                        Column(
                                          crossAxisAlignment:
                                              CrossAxisAlignment.start,
                                          mainAxisAlignment:
                                              MainAxisAlignment.center,
                                          children: [
                                            Text(
                                              "Name: " +
                                                  list[index].name.toString(),
                                              style: TextStyle(
                                                fontFamily: "Inter",
                                                fontSize: 20,
                                                fontWeight: FontWeight.w400,
                                              ),
                                            ),
                                            SizedBox(
                                              height: 10,
                                            ),
                                            Text(
                                              "Experince: " +
                                                  list[index]
                                                      .experince
                                                      .toString() +
                                                  "+ years",
                                              style: TextStyle(
                                                fontFamily: "Inter",
                                                fontSize: 20,
                                                fontWeight: FontWeight.w400,
                                              ),
                                            ),
                                            SizedBox(
                                              height: 10,
                                            ),
                                            Text(
                                              "Number: " +
                                                  list[index].phone.toString(),
                                              style: TextStyle(
                                                fontFamily: "Inter",
                                                fontSize: 20,
                                                fontWeight: FontWeight.w400,
                                              ),
                                            ),
                                            SizedBox(
                                              height: 10,
                                            ),
                                            Text(
                                              "Address: " +
                                                  list[index]
                                                      .address
                                                      .toString(),
                                              style: TextStyle(
                                                fontFamily: "Inter",
                                                fontSize: 20,
                                                fontWeight: FontWeight.w400,
                                              ),
                                            ),
                                          ],
                                        )
                                      ],
                                    )
                                  ],
                                ),
                              ),
                            );
                          });
                    }
                  })
            ],
          ),
        ),
      ),
    );
  }
}
